# Generated by Django 5.0.1 on 2024-01-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='education/', verbose_name='превью')),
                ('link_video', models.CharField(max_length=150, verbose_name='ссылка на видео')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='link_course',
            field=models.CharField(default=None, max_length=150, verbose_name='ссылка на курс'),
        ),
    ]
